### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by RiRilot** [mule1972/NeoPixelBLVmgn#6]
Would it be possible to make a change to the code so that I can change the direction of rotation of the animation?
I'm using slightly different rings to the BoM and they go round anticlockwise rather than clockwise. This is messing with my chi.

**Comment by mule1972** [comment]
I just uploaded a new beta version in the V3.0 branch which gives you the possibility to change the animation direction (set the setup variables AnimationReverse to true in the "User Config"-section)
Besides this it has many new features for multiple hotend/heater setup and therefore the setup is slighty different.

**Comment by RiRilot** [comment]
Awesome. I will have a play.

**Comment by mule1972** [comment]
Just a warning: the new beta version is running fine on an Arduino Mega, but I just recognized that its not working on an Arduino Nano. Dont know yet what's going on.

**Comment by RiRilot** [comment]
OK, I'll hang fire then. I've not got a spare Mega to test with at the moment as they're all tied up doing other things.

**Comment by mule1972** [comment]
I just uploaded a nearly complete rewrite of the code in V3 branch in order to heavily reduce memory needed so that the new code runs on the small Arduinos (Nano, Pro) too.
You can use the config parameter "reverse" in the user config section at the beginning of the code in order to change the direction.
If you have any question regarding the config parameters dont hesitate to ask.

**Comment by RiRilot** [comment]
Awesome. I will have a play soon and post any feedback I have.

**Comment by mule1972** [comment]
I just uploaded another version under V3 branch. This should be the final one if you do not find any bugs.

!Attention! Important config changes:
=> the format for the parameter _ShowHeaters in the user config section has been changed from e.g. "0&1" to 0,1
=> the color scheme config for the heaters has been seperated from the neopixel config section to allow "independent heater config" (see below)

New Features/Updates:
- Independent heater config: If you share one Neopixel to display the status for more than one heater you can now use different color schemes for each heater.
- Add support fo Arduino Due
- Bugfixes

**Comment by RiRilot** [comment]
Hiya
   I built the previous version yesterday and tested. I love the startup animation.
I found 1 issue.
When setting brightness to 128, the bed and status rings work fine but the hot end ring displays garbage. Putting it back lower than 128 sorts it immediately.
Not sure whether this is a problem with my setup or not through.

**Comment by mule1972** [comment]
Thanks for your feedback.
Would be great if you could post your user config section which leads to garbage being displayed.
Which version of the NeopixelLibrary are you using?

**Comment by mule1972** [comment]
I just uploaded the final of the final version ;-)
Once again I had to change the structure of the User Config Section (I promise for the last time). But now everyone has full control of what content is being displayed on which Neopixel and how the content is being displayed (see changelog below for a detailed description).
Would be glad if you could test it with your setup. Once again: If you have any questions regarding the config section: Dont hesitate to ask me!

Changelog:
- Introduction of sharing a single Neopixel to display "multiple PrinterObjects" by seperating Neopixel-Config from PrinterObjects-Config in order to allow full flexibility. PrinterObjects are: Printerstatus (including Printprogress), Bedheater and Heater1-4. This allows to use a single Neopixel to display e.g. the Printerstatus, the bedheater and heater of hotend2 => "Multiple PrinterObjects".
If using a single Neopixel to display more than one PrinterObject you can decide how the Neopixel changes between the different PrinterObjects: 
1. change by frequency (frequency in seconds is configurable by user) 
2. change depending on heater status (only possible if the Neopixel is configured to to only display PrinterObjects of the HeaterClass (BedHeater and Heater 1-4) 
- Restructured code for better readability
- Restructered code to save even more memory
- Improve performance

**Comment by mule1972** [comment]
Just uploaded Beta17 which fixes a serious bug if using multiple hotends and adds the possibility to change the colors of the startup animation in user config section:
#define NeoPixelStartupAnimationColor1 255,0,0  //RGB values for Startup Animation Type1
#define NeoPixelStartupAnimationColor2 0,255,0  //RGB values for Startup Animation Type2
#define NeoPixelStartupAnimationColor3 0,0,255  //RGB values for Startup Animation Type3
